on:
  push:
name: build_arm64
jobs:
  build:
    name: build_arm64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          
          githubToken: ${{ github.token }}
          
          install: |
            apt-get -y update;
            apt-get install -q -y git golang-go;
            apt-get install -y bats golang make openssl swtpm tpm2-tools qemu-kvm
      - name: build
        run: |
          make
      - name: test
        run: |
          make test
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: trust
